# Generated by Django 5.2.15 on 2026-09-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('simbolo', models.CharField(blank=True, max_length=5)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'core_moneda',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'db_table': 'core_tipo_cambio',
                'ordering': ['-fecha', 'moneda_origen'],
                'indexes': [models.Index(fields=['empresa', 'moneda_origen', 'moneda_destino', '-fecha'], name='tipo_cambio_par_fecha_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'moneda_origen', 'moneda_destino', 'fecha'), name='tipo_cambio_unico_por_empresa_par_fecha'), models.CheckConstraint(condition=models.Q(('moneda_origen', models.F('moneda_destino')), _negated=True), name='tipo_cambio_origen_distinto_de_destino')],
            },
        ),
    ]
