# Generated by Django 5.2.15 on 2026-09-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'db_table': 'idio_idioma',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecursoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('modulo', models.CharField(blank=True, max_length=100)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='idiomas.idioma')),
            ],
            options={
                'verbose_name': 'Recurso de texto',
                'verbose_name_plural': 'Recursos de texto',
                'db_table': 'idio_recurso_texto',
                'ordering': ['modulo', 'clave'],
                'constraints': [models.UniqueConstraint(fields=('clave', 'idioma'), name='recurso_texto_unico_por_clave_idioma')],
            },
        ),
        migrations.CreateModel(
            name='Traduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_tipo', models.CharField(max_length=100)),
                ('entidad_id', models.IntegerField()),
                ('campo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('empresa', models.ForeignKey(blank=True, help_text='Vacío = traducción de fábrica, igual para todas las empresas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='empresas.empresa')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='idiomas.idioma')),
            ],
            options={
                'verbose_name': 'Traducción',
                'verbose_name_plural': 'Traducciones',
                'db_table': 'idio_traduccion',
                'ordering': ['entidad_tipo', 'entidad_id', 'campo'],
                'indexes': [models.Index(fields=['entidad_tipo', 'campo', 'idioma', 'entidad_id'], name='traduccion_busqueda_por_lote')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'entidad_tipo', 'entidad_id', 'campo', 'idioma'), name='traduccion_unica_por_empresa'), models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('entidad_tipo', 'entidad_id', 'campo', 'idioma'), name='traduccion_de_fabrica_unica')],
            },
        ),
    ]
