# Generated by Django 5.2.15 on 2026-09-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrupador', models.IntegerField(db_index=True)),
                ('indice', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(blank=True, max_length=20)),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('empresa', models.ForeignKey(blank=True, help_text='Vacío = catálogo del sistema, igual para todas las empresas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Tipología',
                'verbose_name_plural': 'Tipologías',
                'db_table': 'conf_tipologia',
                'ordering': ['agrupador', 'indice', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipologiaOculta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='empresas.empresa')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tipologias.tipologia')),
            ],
            options={
                'verbose_name': 'Tipología oculta para la empresa',
                'verbose_name_plural': 'Tipologías ocultas para la empresa',
                'db_table': 'conf_tipologia_oculta',
            },
        ),
        migrations.CreateModel(
            name='EmpresaAgrupador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrupador', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Lista ampliable por la empresa',
                'verbose_name_plural': 'Listas ampliables por la empresa',
                'db_table': 'conf_empresa_agrupador',
                'ordering': ['empresa', 'agrupador'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'agrupador'), name='empresa_agrupador_unico')],
            },
        ),
        migrations.AddIndex(
            model_name='tipologia',
            index=models.Index(fields=['empresa', 'agrupador'], name='conf_tipolo_empresa_919848_idx'),
        ),
        migrations.AddConstraint(
            model_name='tipologia',
            constraint=models.UniqueConstraint(fields=('empresa', 'agrupador', 'nombre'), name='tipologia_unica_por_empresa_agrupador'),
        ),
        migrations.AddIndex(
            model_name='tipologiaoculta',
            index=models.Index(fields=['empresa', 'tipologia'], name='conf_tipolo_empresa_eb850f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tipologiaoculta',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipologia'), name='tipologia_oculta_unica'),
        ),
    ]
