# Generated by Django 5.2.15 on 2026-09-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('tipologias', '0001_initial'),
        ('tipos_documento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(blank=True, max_length=20)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa')),
                ('estado', models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipos_documento.tipodocumentocomercial')),
            ],
            options={
                'verbose_name': 'Serie documental',
                'verbose_name_plural': 'Series documentales',
                'db_table': 'serv_serie_documental',
            },
        ),
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField()),
                ('ultimo_numero', models.IntegerField(default=0)),
                ('serie_documental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='numeracion.seriedocumental')),
            ],
            options={
                'verbose_name': 'Correlativo',
                'verbose_name_plural': 'Correlativos',
                'db_table': 'serv_correlativo',
            },
        ),
        migrations.AddConstraint(
            model_name='seriedocumental',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'prefijo'), name='serie_documental_unica_por_tipo_y_prefijo'),
        ),
        migrations.AddConstraint(
            model_name='correlativo',
            constraint=models.UniqueConstraint(fields=('serie_documental', 'gestion'), name='correlativo_unico_por_serie_y_gestion'),
        ),
    ]
