# Generated by Django 5.2.15 on 2026-09-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pais', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'core_pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(default=1)),
                ('division_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisiones', to='geografia.ubicaciongeografica')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='geografia.pais')),
            ],
            options={
                'verbose_name': 'Ubicación geográfica',
                'verbose_name_plural': 'Ubicaciones geográficas',
                'db_table': 'core_ubicacion_geografica',
                'ordering': ['pais', 'nivel', 'nombre'],
                'indexes': [models.Index(fields=['pais', 'nivel'], name='core_ubicac_pais_id_de34f4_idx'), models.Index(fields=['division_superior'], name='core_ubicac_divisio_82276f_idx')],
            },
        ),
    ]
