# Generated by Django 5.2.15 on 2026-09-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaCruzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_origen', models.CharField(max_length=30)),
                ('tabla_origen', models.CharField(max_length=63)),
                ('registro_origen_id', models.IntegerField()),
                ('modulo_destino', models.CharField(max_length=30)),
                ('tabla_destino', models.CharField(max_length=63)),
                ('registro_destino_id', models.IntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa')),
                ('estado', models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('tipo_vinculo', models.ForeignKey(help_text='AGRUPADOR.TIPO_VINCULO — genera, respalda, deriva de…', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
            ],
            options={
                'verbose_name': 'Referencia cruzada',
                'verbose_name_plural': 'Referencias cruzadas',
                'db_table': 'serv_referencia_cruzada',
                'indexes': [models.Index(fields=['empresa', 'tabla_origen', 'registro_origen_id'], name='ref_cruzada_por_origen'), models.Index(fields=['empresa', 'tabla_destino', 'registro_destino_id'], name='ref_cruzada_por_destino')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tabla_origen', 'registro_origen_id', 'tabla_destino', 'registro_destino_id', 'tipo_vinculo'), name='referencia_cruzada_sin_repetir')],
            },
        ),
    ]
