

limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

server {
    listen 8080;
    server_name erp.com.bo;
    client_max_body_size 20M;

    location /graphql/ {
        limit_req zone=api_limit burst=10 nodelay;
        proxy_pass http://erp-backend:8000/graphql/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # location /api/ {
    #     limit_req zone=api_limit burst=10 nodelay;
    #     proxy_pass http://portaldatos-backend:8000/api/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }



    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}