# Generated by Django 5.2.15 on 2026-09-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_moneda_oficial', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Moneda de la empresa',
                'verbose_name_plural': 'Monedas de la empresa',
                'db_table': 'core_empresa_moneda',
            },
        ),
        migrations.CreateModel(
            name='EmpresaPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('logo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'País de la empresa',
                'verbose_name_plural': 'Países de la empresa',
                'db_table': 'core_empresa_pais',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_tributaria', models.CharField(db_index=True, max_length=30)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('empresa_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'core_empresa',
                'ordering': ['razon_social'],
            },
        ),
    ]
