# Generated by Django 5.2.15 on 2026-09-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('geografia', '0001_initial'),
        ('idiomas', '0001_initial'),
        ('monedas', '0001_initial'),
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='idioma_default',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='idiomas.idioma'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubicacion_geografica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geografia.ubicaciongeografica'),
        ),
        migrations.AddField(
            model_name='empresamoneda',
            name='empresa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='empresamoneda',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='empresamoneda',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='monedas.moneda'),
        ),
        migrations.AddField(
            model_name='empresapais',
            name='empresa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='empresapais',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geografia.pais'),
        ),
        migrations.AddField(
            model_name='empresapais',
            name='ubicacion_geografica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geografia.ubicaciongeografica'),
        ),
        migrations.AddConstraint(
            model_name='empresamoneda',
            constraint=models.UniqueConstraint(fields=('empresa', 'moneda'), name='empresa_moneda_unica'),
        ),
        migrations.AddConstraint(
            model_name='empresapais',
            constraint=models.UniqueConstraint(fields=('empresa', 'pais'), name='empresa_pais_unico'),
        ),
    ]
