# Generated by Django 5.2.15 on 2026-09-09 03:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoDeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permiso de negocio',
                'verbose_name_plural': 'Permisos de negocio',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DispositivoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('ultima_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(verbose_name='desde')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='hasta')),
            ],
            options={
                'verbose_name': 'Dispositivo autorizado',
                'verbose_name_plural': 'Dispositivos autorizados',
                'db_table': 'segu_dispositivo_usuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='GrupoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rol de empresa',
                'verbose_name_plural': 'Roles de empresa',
                'db_table': 'segu_grupo_empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoEmpresaPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permiso del rol',
                'verbose_name_plural': 'Permisos del rol',
                'db_table': 'segu_grupo_empresa_permiso',
            },
        ),
        migrations.CreateModel(
            name='GrupoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='desde')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='hasta')),
                ('motivo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Rol asignado',
                'verbose_name_plural': 'Roles asignados',
                'db_table': 'segu_grupo_usuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='0 = lunes … 6 = domingo (convención de date.weekday()).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='desde')),
                ('hora_fin', models.TimeField(verbose_name='hasta')),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Horario de acceso',
                'verbose_name_plural': 'Horarios de acceso',
                'db_table': 'segu_horario_acceso',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioExcepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='desde')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='hasta')),
                ('motivo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Excepción de horario',
                'verbose_name_plural': 'Excepciones de horario',
                'db_table': 'segu_horario_excepcion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SesionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('refresh_jti', models.CharField(blank=True, db_index=True, max_length=32)),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'db_table': 'segu_sesion_acceso',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificador', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa')),
                ('estado', models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('tipo', models.ForeignKey(help_text='AGRUPADOR.TIPO_DISPOSITIVO', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'segu_dispositivo',
                'ordering': ['nombre'],
            },
        ),
    ]
