# Generated by Django 5.2.15 on 2026-09-09 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresas', '0002_initial'),
        ('membresias', '0002_initial'),
        ('seguridad', '0001_initial'),
        ('tipologias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivousuario',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispositivousuario',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='seguridad.dispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivousuario',
            name='estado',
            field=models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='dispositivousuario',
            name='usuario_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='membresias.usuarioempresa'),
        ),
        migrations.AddField(
            model_name='grupoempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='grupoempresa',
            name='estado',
            field=models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='grupoempresapermiso',
            name='auth_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='grupoempresapermiso',
            name='grupo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='seguridad.grupoempresa'),
        ),
        migrations.AddField(
            model_name='grupousuario',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupousuario',
            name='estado',
            field=models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='grupousuario',
            name='grupo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='seguridad.grupoempresa'),
        ),
        migrations.AddField(
            model_name='grupousuario',
            name='usuario_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='membresias.usuarioempresa'),
        ),
        migrations.AddField(
            model_name='horarioacceso',
            name='estado',
            field=models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='horarioacceso',
            name='usuario_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='membresias.usuarioempresa'),
        ),
        migrations.AddField(
            model_name='horarioexcepcion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='membresias.usuarioempresa'),
        ),
        migrations.AddField(
            model_name='horarioexcepcion',
            name='estado',
            field=models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='horarioexcepcion',
            name='tipo',
            field=models.ForeignKey(help_text='AGRUPADOR.TIPO_EXCEPCION_HORARIO — PERMISO o BLOQUEO.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='horarioexcepcion',
            name='usuario_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='membresias.usuarioempresa'),
        ),
        migrations.AddField(
            model_name='sesionacceso',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='seguridad.dispositivo'),
        ),
        migrations.AddField(
            model_name='sesionacceso',
            name='empresa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='sesionacceso',
            name='estado',
            field=models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='sesionacceso',
            name='resultado',
            field=models.ForeignKey(help_text='AGRUPADOR.RESULTADO_ACCESO', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='sesionacceso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('mac', ''), _negated=True), fields=('empresa', 'mac'), name='dispositivo_mac_unica_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('identificador', ''), _negated=True), fields=('empresa', 'identificador'), name='dispositivo_identificador_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='dispositivousuario',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='dispositivo_usuario_fechas_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='grupoempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='grupo_empresa_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='grupoempresapermiso',
            constraint=models.UniqueConstraint(fields=('grupo_empresa', 'auth_permission'), name='permiso_unico_por_rol'),
        ),
        migrations.AddConstraint(
            model_name='grupousuario',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='grupo_usuario_fechas_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='horarioacceso',
            constraint=models.CheckConstraint(condition=models.Q(('vigencia_hasta__isnull', True), ('vigencia_hasta__gte', models.F('vigencia_desde')), _connector='OR'), name='horario_acceso_vigencia_coherente'),
        ),
        migrations.AddConstraint(
            model_name='horarioexcepcion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hora_fin__isnull', True), ('hora_inicio__isnull', True)), models.Q(('hora_fin__isnull', False), ('hora_inicio__isnull', False)), _connector='OR'), name='horario_excepcion_horas_completas'),
        ),
        migrations.AddIndex(
            model_name='sesionacceso',
            index=models.Index(fields=['usuario', 'fin'], name='sesion_usuario_abierta_idx'),
        ),
    ]
