# Generated by Django 5.2.15 on 2026-09-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DURA', 'Dura — no funciona sin él'), ('SUAVE', 'Suave — se integra si está')], default='DURA', max_length=10)),
            ],
            options={
                'verbose_name': 'Dependencia entre módulos',
                'verbose_name_plural': 'Dependencias entre módulos',
                'db_table': 'prov_modulo_dependencia',
            },
        ),
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_vendible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Módulo del sistema',
                'verbose_name_plural': 'Módulos del sistema',
                'db_table': 'prov_modulo_sistema',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Submódulo',
                'verbose_name_plural': 'Submódulos',
                'db_table': 'prov_sub_modulo',
                'ordering': ['modulo_sistema__codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Funcionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('auth_permission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funcionalidad', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Funcionalidad',
                'verbose_name_plural': 'Funcionalidades',
                'db_table': 'prov_funcionalidad',
                'ordering': ['sub_modulo__codigo', 'nombre'],
            },
        ),
    ]
