# Generated by Django 5.2.15 on 2026-09-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo_modulos', '0001_initial'),
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionalidad',
            name='estado',
            field=models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='modulosistema',
            name='estado',
            field=models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='modulodependencia',
            name='depende_de',
            field=models.ForeignKey(help_text='El módulo requerido para que el primero funcione.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo_modulos.modulosistema'),
        ),
        migrations.AddField(
            model_name='modulodependencia',
            name='modulo',
            field=models.ForeignKey(help_text='El módulo que declara la dependencia.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogo_modulos.modulosistema'),
        ),
        migrations.AddField(
            model_name='submodulo',
            name='estado',
            field=models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia'),
        ),
        migrations.AddField(
            model_name='submodulo',
            name='modulo_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_modulos', to='catalogo_modulos.modulosistema'),
        ),
        migrations.AddField(
            model_name='funcionalidad',
            name='sub_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionalidades', to='catalogo_modulos.submodulo'),
        ),
        migrations.AddConstraint(
            model_name='modulodependencia',
            constraint=models.UniqueConstraint(fields=('modulo', 'depende_de'), name='modulo_dependencia_sin_repetir'),
        ),
        migrations.AddConstraint(
            model_name='modulodependencia',
            constraint=models.CheckConstraint(condition=models.Q(('modulo', models.F('depende_de')), _negated=True), name='modulo_dependencia_no_se_depende_de_si_mismo'),
        ),
        migrations.AddConstraint(
            model_name='submodulo',
            constraint=models.UniqueConstraint(fields=('modulo_sistema', 'nombre'), name='sub_modulo_nombre_unico_por_modulo'),
        ),
        migrations.AddConstraint(
            model_name='funcionalidad',
            constraint=models.UniqueConstraint(fields=('sub_modulo', 'nombre'), name='funcionalidad_nombre_unico_por_pantalla'),
        ),
    ]
