# Generated by Django 5.2.15 on 2026-09-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('geografia', '0001_initial'),
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('descuento_categ_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lista_precio_id', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa')),
                ('estado', models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
            ],
            options={
                'verbose_name': 'Categoría de entidad',
                'verbose_name_plural': 'Categorías de entidad',
                'db_table': 'ent_categoria_entidad',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pri_apellido', models.CharField(blank=True, max_length=100)),
                ('seg_apellido', models.CharField(blank=True, max_length=100)),
                ('documento', models.CharField(blank=True, max_length=50)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa')),
                ('estado', models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('regimen_tributario', models.ForeignKey(blank=True, help_text='AGRUPADOR.REGIMEN_TRIBUTARIO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('tipo_documento', models.ForeignKey(help_text='AGRUPADOR.TIPO_DOCUMENTO', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('tipo_entidad', models.ForeignKey(help_text='AGRUPADOR.TIPO_ENTIDAD', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'ent_entidad',
            },
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntaje', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entidades.entidad')),
            ],
            options={
                'verbose_name': 'Encuesta de satisfacción',
                'verbose_name_plural': 'Encuestas de satisfacción',
                'db_table': 'ent_encuesta_satisfaccion',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('direccion_texto', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estado', models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('tipo', models.ForeignKey(help_text='AGRUPADOR.TIPO_DIRECCION', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('ubicacion_geografica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geografia.ubicaciongeografica')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entidades.entidad')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'ent_direccion',
            },
        ),
        migrations.CreateModel(
            name='ContactoEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('estado', models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entidades.entidad')),
            ],
            options={
                'verbose_name': 'Contacto de la entidad',
                'verbose_name_plural': 'Contactos de la entidad',
                'db_table': 'ent_contacto_entidad',
            },
        ),
        migrations.CreateModel(
            name='RolEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('datos_rol', models.JSONField(blank=True, default=dict)),
                ('categoria_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entidades.categoriaentidad')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entidades.entidad')),
                ('estado', models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
                ('tipo_rol', models.ForeignKey(help_text='AGRUPADOR.TIPO_ROL', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
            ],
            options={
                'verbose_name': 'Rol de la entidad',
                'verbose_name_plural': 'Roles de la entidad',
                'db_table': 'ent_rol_entidad',
            },
        ),
        migrations.AddConstraint(
            model_name='categoriaentidad',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='categoria_entidad_nombre_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='entidad',
            constraint=models.UniqueConstraint(condition=models.Q(('documento', ''), _negated=True), fields=('empresa', 'documento'), name='entidad_documento_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='rolentidad',
            constraint=models.UniqueConstraint(fields=('entidad', 'tipo_rol'), name='rol_entidad_sin_repetir_el_rol'),
        ),
    ]
