# Generated by Django 5.2.15 on 2026-09-11 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usuarioempresa',
            constraint=models.UniqueConstraint(fields=('usuario', 'empresa'), name='usuario_empresa_unica'),
        ),
    ]
