# Generated by Django 5.2.15 on 2026-09-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('tipologias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('afecta_stock', models.BooleanField(default=False)),
                ('genera_ingreso', models.BooleanField(default=False)),
                ('es_venta', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa')),
                ('estado', models.ForeignKey(help_text='AGRUPADOR.ESTADO_REGISTRO — soft delete, nunca se borra.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tipologias.tipologia')),
            ],
            options={
                'verbose_name': 'Tipo de documento comercial',
                'verbose_name_plural': 'Tipos de documento comercial',
                'db_table': 'vent_tipo_documento_comercial',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='tipo_documento_codigo_unico_por_empresa')],
            },
        ),
    ]
